### ISSUE TITLE
IP Activation Issues

### ISSUE THREAD

**Issue by MK3112** [CelestialInteractive/SAC#14]
**Accidentally logged out and can’t log back in **
Display: (ERROR: CheckAuthentication: AES keys not in session array)

**To Reproduce**
1. Go to 'Log in'
2. Click on 'Sign in'
4. See error: (ERROR: CheckAuthentication: AES keys not in session array) /

**Expected behavior**
Being able to log back in.  

**Screenshots**
![image](https://user-images.githubusercontent.com/41471766/42996961-0acfe7d8-8c0d-11e8-9603-c38d635612ca.png)

**Smartphone (please complete the following information):**
 - Device: Iphone X
 - OS: 11.4.1

**Additional context**
First email: confirming you email address
 - Worked
-  Then couldn’t log back in once logged out.
 - Then got second email (confirming your IP address):
 - ERROR: IP Activation failed, this username is not linked to any account.

**Comment by alexlaurence** [comment]
Thanks for this! I had a look at the database, and Jamie was using different IP addresses. Not sure why the verification email wasn't working (I'll look into it!). But usually, it's best to avoid changing locations - ask patients to stick to home WiFi (avoid 4G).

**Comment by MK3112** [comment]
Yeah mine is working well now and I can log in and out just perfectly for now ☺

**Comment by alexlaurence** [comment]
Thanks for the confirmation, Melanie!

**Comment by MK3112** [comment]
You’re welcome ☺
