### ISSUE TITLE
Display "Storage of data/ entry patient" 

### ISSUE THREAD

**Issue by MK3112** [CelestialInteractive/SAC#20]
**Null is displayed for saved Sleep Diary Data**
It doesn't show which data is saved. 

**Expected behavior**
It should show the responses of the patient and what is saved. 

**Screenshots**
![image](https://user-images.githubusercontent.com/41471766/42999734-dd76eb9c-8c16-11e8-8965-0aed4f9a61b2.png)

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: 11.4.1

**Comment by alexlaurence** [comment]
Hi Melanie, please use the latest build 👍

**Comment by MK3112** [comment]
Cool 😃 will do!
