### ISSUE TITLE
Wrong content for "How does my pain diary work"

### ISSUE THREAD

**Issue by MK3112** [CelestialInteractive/SAC#22]
**wrong content**
Click on "How main pain diary works" = it takes me to the last page of the cortisol information page Hence, there is no information on how the pain diary works in here. 

**To Reproduce**
1. Go to 'How the sleep diary works'
2. Click on 'How main pain diary works'

**Expected behavior**
To show information on how the pain diary works. 

**Screenshots**
![image](https://user-images.githubusercontent.com/41471766/43006049-9dc7c26c-8c2c-11e8-9673-9cc5a4948736.png)

**Smartphone (please complete the following information):**
 - Device: Iphone 6
 - OS: 11.4.1

**Comment by alexlaurence** [comment]
Fixed:)

**Comment by MK3112** [comment]
Amazing ☺
