### ISSUE TITLE
Time Picker Next Button

### ISSUE THREAD

**Issue by MK3112** [CelestialInteractive/SAC#26]
**Next button**
First: Time Picker works and shows Numbers in the text box!
BUT The next button at the time picker does not "block" when no time is filled in. 

Bug for **ALL** Time Picker buttons. 

**To Reproduce**
1. Go to 'Sleep Diary new entry'
2. Click on 'follow Qs until Qs 4 of 14'

**Expected behavior**
The next button at the time picker does not "block" when no time is filled in. 

**Smartphone (please complete the following information):**
 - Device: Iphone 6
 - OS: 11.4.1

**Comment by alexlaurence** [comment]
Well spotted! Thanks Melanie

**Comment by MK3112** [comment]
You’re welcome ☺
