### ISSUE TITLE
Video Link Cortisol doesn't work

### ISSUE THREAD

**Issue by MK3112** [CelestialInteractive/SAC#30]
**Hyperlink doesn't work**
Video Link Cortisol doesn't work/ doesn't open ? 

**To Reproduce**
1. Go to 'More information'
2. Click on 'Cortisol'
3. Move to 3rd page
4. See error: Click on "Watch Video Instructions" = Link does not open 

**Expected behavior**
Link should open or you should be able to watch the video.

**Smartphone (please complete the following information):**
 - Device: Iphone 6
 - OS: 11.4.1

**Comment by alexlaurence** [comment]
Hi Melanie, just to check: do you have the YouTube app installed?

**Comment by MK3112** [comment]
I do not have youtube on my phone. But do you think we can rely on people having youtube on their phones usually? (I think I deleted mine)

**Comment by alexlaurence** [comment]
Ahh ok! I'll make it open the weblink instead :)

**Comment by MK3112** [comment]
Thanks :-)!

Melanie Koelbel, PhD student

Developmental Neurosciences Programme
UCL Great Ormond Street Institute of Child Health
30 Guilford Street | London | WC1N 1EH

________________________________

**Comment by alexlaurence** [comment]
Fixed!:)

**Comment by MK3112** [comment]
Thanks so much again ☺ !

**Comment by MK3112** [comment]
Worked well :) !
