### ISSUE TITLE
Question: Contact information button 

### ISSUE THREAD

**Issue by MK3112** [CelestialInteractive/SAC#35]
I really like the contact information button, a great idea.  So the patient can just write the message into the box and it will be automatically sent to me and Fen? That’s really cool 😃

**Comment by alexlaurence** [comment]
Thanks Melanie! Yeah it sends to both you and Fen. I haven't tested it out yet, so let  me know if it works :)

**Comment by MK3112** [comment]
Great I will try it with the next IOS download 😃

Thanks again!
