### ISSUE TITLE
More info button has wrong content 

### ISSUE THREAD

**Issue by MK3112** [CelestialInteractive/SAC#37]
**wrong content**
More info button has wrong content More info button has wrong content 

**To Reproduce**
1. Go to 'More Info'
2. See error: Shows content of "Contact Information" 

**Expected behavior**
Should show content of "Information" page. 

**Screenshots**
Note: I just blacked out the address. 
![image](https://user-images.githubusercontent.com/41471766/43035792-4d6dbc2e-8ced-11e8-8010-d9d292912dc5.png)

**Smartphone (please complete the following information):**
 - Device: Iphone 6
 - OS: 11.4.1.

**Comment by alexlaurence** [comment]
Hi Melanie, I'm not sure what the bug is here, could you explain more for me? :)

**Comment by MK3112** [comment]
Yes, so when you tab on the “More info button” usually it should open the page with “Information” and the buttons that you can press to get infor on “My sleep diary”, “Cortisol” and so on, but instead when I tab the “More info button” it directs me to the “contact information content page (i.e, where I can send an e-mail to me and Fen).

Does it make sense? ☺

**Comment by alexlaurence** [comment]
Thanks! Fixed:)

**Comment by MK3112** [comment]
Great ☺ Thanks a lot!
