### ISSUE TITLE
jump question gender

### ISSUE THREAD

**Issue by MK3112** [CelestialInteractive/SAC#47]
**jump question**
Question 1 of 26: When you click "prefer not to answer it jumps top (see screenshot) 

**To Reproduce**
1. Go to 'register as new patient'
Start to fill in PreLim Qs

**Expected behavior**
move to Qs 2of 26 (i.e., next question). 

**Screenshots**
![file](https://user-images.githubusercontent.com/41471766/43049335-a5e57378-8ded-11e8-9d07-bc4177ed5230.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone 6
 - OS: 11.4.1

**Comment by alexlaurence** [comment]
This one made me laugh haha. What a naughty bug! Fixed :) Well spotted as always!

**Comment by MK3112** [comment]
Haha your welcome. I have become an excellent bug finder 😃
