### ISSUE TITLE
wrong button Qs 8 of 13 Sleep Diary

### ISSUE THREAD

**Issue by MK3112** [CelestialInteractive/SAC#48]
**Wrong button**
wrong button Qs 8 of 13 Sleep Diary ( send them in my last e-mail to Alexander Laurence <a.laurence@celestial.tokyo> at 14:54

**To Reproduce**
1. Go to 'My Sleep Diary '
2. Click on 'all the questions until Qs 8 of 13'
"If you had difficulty...." 

**Expected behavior**
Please change button 

**Screenshots**
Wrong buttons for **Pain** and **Worries** 
![file-1](https://user-images.githubusercontent.com/41471766/43049381-e8195984-8dee-11e8-8e7c-a43a4213d59c.jpeg)

Please change to buttons: 
**Pain**
<img width="640" alt="pain_button" src="https://user-images.githubusercontent.com/41471766/43049388-fd4d8186-8dee-11e8-8883-50f8522cafd7.png">

**Worries**
<img width="652" alt="worries_button" src="https://user-images.githubusercontent.com/41471766/43049389-ffbc99b6-8dee-11e8-942d-851173242ed6.png">

**Smartphone (please complete the following information):**
 - Device: iPhone 6
 - OS: 11.4.1.

**Comment by alexlaurence** [comment]
Hi Melanie, thanks for this. Could you send me the auto-cropped version of these buttons? They still have whitespace on them... Maybe Gimp didn't auto-crop properly.

**Comment by MK3112** [comment]
Oh really I thought it did, darn it. Will do now ☺

**Comment by alexlaurence** [comment]
Thanks so much!!

**Comment by MK3112** [comment]
No problem. Let me know of there is anything else I can do. Gimp is striking at the moment. Might take a couple of minutes lol

**Comment by alexlaurence** [comment]
All done!

**Comment by MK3112** [comment]
Awesome ☺
