### ISSUE TITLE
Wrong back button content

### ISSUE THREAD

**Issue by MK3112** [CelestialInteractive/SAC#49]
**Wrong back button**
When I push the back button on Qs 8 of 13 it jumps to Qs 7 of 13 (the one that we "deleted" / jumped)

**To Reproduce**
1. Go to 'My Sleep Diary'
2. Click on '.fill in all the questions until 8 of 13 and push back'
3. See error: shows Qs 7 of 13

**Expected behavior**
should return to Qs 6 of 13

**Screenshots**
![file-3](https://user-images.githubusercontent.com/41471766/43049426-c0770312-8def-11e8-9cff-51904277aef2.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone 6
 - OS: 11.4.1

**Comment by alexlaurence** [comment]
Oh forgot about that! Fixed now :)

**Comment by MK3112** [comment]
Thanks ☺
