### ISSUE TITLE
Link to video for MRI ?

### ISSUE THREAD

**Issue by MK3112** [CelestialInteractive/SAC#55]
I was wondering if you maybe could add the link to the MRI info: 
I think its a cute video explaining the MRI in a child friendly way, plus you don't have to create a new page :) 
what do you think? The words in bold are new, please add. 

MRI: The scan will take about 45 min to complete. An MRI (magnetic resonance imaging) scan uses a magnetic field rather than x-rays to take pictures. It will give us an insight in your brains structure and function. **Please follow the link for a short cartoon video on the MRI : https://www.youtube.com/watch?v=Q_Pa6KFL1Nw**

**Comment by alexlaurence** [comment]
Hi Melanie! I'm out of screen space on the info menu for MRI. Can't fit another button for MRI. Should I add it in another section?
